# -*- coding: utf-8 -*-
"""PythonBasicsAssignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nmsJk8i17_IiHVDyweauqrpkx97HqTrK

## **Question 1 : What is Python and why is it widely used in Data Analytics? Mention any three reasons.**

*Ans* - Python is a high level programming language which is easy to interpret and learn, it is also higly rated for it's simple syntax, redablity, and versatility. It is commonly use for alsmost everything whether form making website to Data analysis and training Ai models.
It is often called as "beginner friendly language" for all of it's characteristics which makes it easy to understand and learn for a person who never did programming before.

#### **Three reasons why python is used for Data Analysis** -

*   Beginner friendly which makes it easy to learn for non programmers as it has very simple and readable syntax which sees as good start for new learner.

*   Python use natural language sturcture where indentation  makes the code redable.

*   Python has a large community support with Libraries like Pandas, NumPy, Matplotlib, and Scikit-Learn which is commonly used in Data Analysis.

## **Question 2 : Explain the difference between List and Tuple in Python.**

*Ans* - **List** :
*    **Definition**- List is an ordered collection of item, where each items can be of any data type ( eg. Interger or Strings. ), a list is written in using square brackets [ ]
*    **Mutation**- Mutaion can be possible inside a list that means items can be added, removed or changed.
*    **Indexed**- Any items inside the list can be accessed using their position in the list.
*    **Duplicacy**- Items inside a list can have duplicate values.
       
       **Tuple**:
*    **Definition**- Tuple is a type of data in which mutaion is not possible, that means items inside a tuple can't be added, removed or modified. A Tuple can be written using ( ) round brackets.
*    **Usage**-it is manly used when you need to have a fixed collection of items which won't change. for e.g. co-ordinates, configuration setting or dictionary keys.
*    **Indexed**- Like List indexing is also possible inside a Tuple as the items are fixed in their position.
*    **Duplicacy**- Items inside a Tuple can have duplicate values like List.

## **Question 3 : What is a function in Python? Why are functions useful?**

*Ans*- A Function is a block of code which is organised and reusable that can perform a specific tast. Purpose of a function is to enable modularity, reduce redundancy, and improve code clarity.

There are majourly five types of Function:-

*   Buid-in Functions
*   User-defined Functions
*   Lambda ( Anonymous ) Functions
*   Recursive Functions
*   High Order Functions

## **Question 4 : Write a Python program to take a user's name as input and print a greeting message.**
"""

# Ans

Name = input("What is your Name? ")
print('Hellow!',Name)

"""## **Question 5 : Write a Python program to check whether a number is even or odd using conditional statements.**"""

# Ans

for List in range(1,21):
  if List % 2 == 0:
    print(List, '- Even')
  else:
    print(List, '- Odd')

"""## **Question 6 : Write a program to print numbers from 1 to 10 using a loop.**

"""

# Ans

for i in range(1, 11):
  print(i)

"""## **Question 7 : Create a list of five numbers and print the maximum number from the list.**"""

# Ans

a = [22, 25, 30, 16, 10]
max(a)

"""## **Question 8 : Write a Python program to remove duplicate values from a list using a set.**"""

# Ans


"""In a set there are no duplicate values are acceptable,
it will automatically remove those duplicate values itself and place them in
an order.
in this example 5, 7, 8, 12, 15, and 19 used more than one time."""


dupliace_value = {5, 12, 8, 5, 19, 7, 12, 3, 15, 8, 21, 4, 19, 10, 6, 15, 2, 7, 14, 5}
dupliace_value

"""## **Question 9 : Write a function that returns the square of a number.**"""

# Ans

def Square(n):
  return(n*n)

Square(49)

"""## **Question 10 : Write a Python program to count how many times a number appears in a list. Example List- [2,3,4,2,5,2]**"""

# Ans

count_num = [2,3,4,2,5,2]
print(count_num.count(2))